# Generated by Django 4.2.2 on 2023-07-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500, null=True)),
                ('img_local', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'db_table': '"traveldata"."cities"',
            },
        ),
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('img', models.CharField(max_length=500, null=True)),
                ('img_local', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.cities')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, null=True)),
            ],
            options={
                'db_table': '"traveldata"."sights"',
                'ordering': ['-popularity', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Sights_texts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('tele', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=10000, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.cities')),
            ],
            options={
                'db_table': '"traveldata"."sights_texts"',
            },
        ),
        migrations.CreateModel(
            name='Sights_imgs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500, null=True)),
                ('img_local', models.CharField(max_length=500, null=True)),
                ('sights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.sights')),
            ],
            options={
                'db_table': '"traveldata"."sights_imgs"',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500)),
                ('rank', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('img', models.CharField(max_length=500, null=True)),
                ('img_local', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.cities')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, null=True)),
            ],
            options={
                'db_table': '"traveldata"."shops"',
                'ordering': ['-rank', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('address_link', models.CharField(max_length=500, null=True)),
                ('img', models.CharField(max_length=500, null=True)),
                ('img_local', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.cities')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, null=True)),
            ],
            options={
                'db_table': '"traveldata"."foods"',
            },
        ),
    ]
