# Generated by Django 4.2.2 on 2023-08-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traveldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Awesome place!', max_length=1000)),
                ('rating', models.SmallIntegerField(default=2)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveldata.sights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"journingdata"."comments"',
                'ordering': ['-created_on'],
            },
        ),
    ]
